CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(50) UNIQUE NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "level_id" int NOT NULL,
  "user_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar(30) NOT NULL,
  "lastname" varchar(30) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(30) UNIQUE NOT NULL,
  "age" varchar(30) UNIQUE NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "user_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_course" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_course" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

/* INSERT INFO TO TABLES */

/* ROLES */
SELECT * FROM roles;
INSERT INTO roles (name) VALUES ('Student'), ('Teacher'), ('Admin');

/* CATEGORIES */
SELECT * FROM categories;
INSERT INTO categories (name) VALUES ('Frontend'), ('Backend'), ('Fullstack');

/* LEVELS */
SELECT * FROM levels;
INSERT INTO levels (level) VALUES ('Begginer'), ('Intermediate'), ('Advance');

/* USERS */
SELECT * FROM users;
INSERT INTO users (firstname, lastname, email, password, age, role_id)
VALUES ('Jose', 'Garcia', 'jose@mail.com', 'Afdr1496', '28', 1),
('Luis', 'Ramirez', 'luis@mail.com', 'Gdgdf155', '20', 1),
('Victor', 'Roman', 'victor@mail.com', 'Igtyf454', '25', 1);

/* COURSES */
SELECT * FROM courses;
INSERT INTO courses (title, description, level_id, user_id, category_id)
VALUES ('Fundamentals', 'Learn HTML CSS and JS', 1, 1, 1),
('ReactJS', 'Design web application with react', 2, 2, 1),
('NodeJS', 'Create your own database', 2, 3, 2);

/* USER_COURSE */
SELECT * FROM user_course;
INSERT INTO user_course (user_id, course_id) VALUES (1, 1), (2, 1), (3, 1);

/* COURSE_VIDEO */
SELECT * FROM course_video;
INSERT INTO course_video (title, url, course_id)
VALUES ('HTML CSS JS from cero', 'https//fundamentals', 1),
('React with redux', 'https//react/redux', 2),
('NodeJs with express', 'https//node/express', 3);